name: Xuxemons

services:
  db:
    container_name: xuxemons_db
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: xuxemons
      MYSQL_USER: xuxemons_user
      MYSQL_PASSWORD: 1234
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - xuxemons_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p1234" ]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    container_name: xuxemons_laravel
    build: ./backend
    ports:
      - "8000:80"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/var/www/html
    networks:
      - xuxemons_network
    environment:
      TZ: Europe/Madrid
    command: >
      bash -c " curl -sS https://getcomposer.org/installer | php --
      --install-dir=/usr/local/bin --filename=composer  && composer install &&
      php artisan migrate && php artisan db:seed && apache2-foreground "

  frontend:
    container_name: xuxemons_angular
    image: node:20
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    working_dir: /app
    networks:
      - xuxemons_network
    command: >
      bash -c "npm install && npx ng serve --host 0.0.0.0 --port 4200"

  scheduler:
    container_name: xuxemons_scheduler
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/var/www/html
    networks:
      - xuxemons_network
    environment:
      TZ: Europe/Madrid
    command: >
      bash -c " curl -sS https://getcomposer.org/installer | php --
      --install-dir=/usr/local/bin --filename=composer && composer install &&
      while true; do php artisan schedule:run; sleep 60; done "

volumes:
  db_data:

networks:
  xuxemons_network:
    driver: bridge
